---
version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: monthly
      time: '12:00'
    open-pull-requests-limit: 10
    labels:
      - task
      - dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
      time: '12:00'
    open-pull-requests-limit: 10
    labels:
      - task
      - dependencies
      - automerge
