name: Auto-merge

on:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened

jobs:
  auto-merge:
    name: 'Auto-merge'
    runs-on: ubuntu-latest
    permissions: write-all

    if: github.event.pull_request.user.login == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'automerge')
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.1.2
        timeout-minutes: 15
        with:
          ref: ${{ github.ref }}
          running-workflow-name: 'Auto-merge'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success
      - uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          number: ${{ github.event.number }}
          method: squash
          repo: dnsimple/dnsimple-ruby
